name: Version Increment

on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[RELEASE]') }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git config --global user.name 'mandragora-hub'
      - run: git config --global user.email 'royer01gomez@gmail.com'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
      - run: git push --tags
